default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.16
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [requirements.in, -o, requirements.txt]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run isort
        types: [python]
        language: system

      - id: pydocstyle
        name: pydocstyle
        entry: uv run pydocstyle --convention=google .
        types: [python]
        language: system
