name: build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
          - windows-2022
          - macos-latest
          - macos-13
          - macos-12
        python-version: ["3.12"]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.platform }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Cache Cargo
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Install bun, cargo, and uv
        run: |
          make bun-download
          make cargo-download
          make uv-download

      - name: Install dependencies
        run: |
          make install

      - name: Run style checks
        run: |
          make check-codestyle

      - name: Run docstrings checks
        run: |
          make docs

      - name: Run tests
        run: |
          make test
